/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register
     * @description Register a new user.
     *
     *     - Checks if email is already taken
     *     - Hashes the password
     *     - Saves user to database
     */
    post: operations["register_auth_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description Login and get a JWT token.
     *
     *     - Verifies email and password
     *     - Returns access token
     */
    post: operations["login_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/verify-email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Verify Email
     * @description Verifies a user's email with the token sent to them.
     */
    get: operations["verify_email_auth_verify_email_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Forgot Password
     * @description Sends a password reset email if the user exists.
     */
    post: operations["forgot_password_auth_forgot_password_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset Password
     * @description Resets user's password using the token.
     */
    post: operations["reset_password_auth_reset_password_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Current User Info
     * @description Get current logged-in user's information.
     *
     *     This route is PROTECTED - requires valid JWT token.
     */
    get: operations["get_current_user_info_auth_me_get"];
    /**
     * Update Current User Info
     * @description Update current logged-in user's profile information.
     */
    put: operations["update_current_user_info_auth_me_put"];
    post?: never;
    /**
     * Delete Current User
     * @description Permanently delete the authenticated user's account and all associated data.
     *     Requires password confirmation.
     */
    delete: operations["delete_current_user_auth_me_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/content": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Content Items
     * @description List all content items for current user.
     *
     *     - Supports pagination (skip/limit)
     *     - Filter by read/archived status
     *     - Filter by tag
     *     - Excludes soft-deleted items
     */
    get: operations["list_content_items_content_get"];
    put?: never;
    /**
     * Create Content Item
     * @description Save a new link/article.
     *
     *     - Creates content item with status 'pending'
     *     - Trigger background job to extract metadata/full text
     *     - Optionally adds to specified lists
     */
    post: operations["create_content_item_content_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/content/tags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get User Tags
     * @description Get all unique tags for the current user with occurrence counts.
     *     Returns list of (tag, count) tuples, sorted by frequency.
     */
    get: operations["get_user_tags_content_tags_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/content/recommended": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Recommended Content
     * @description Get recommended content items for the user.
     *
     *     Scoring factors (no ML):
     *     - Embedding similarity to recently read articles
     *     - Reading time match (based on user's patterns)
     *     - Recency (newer articles scored higher with decay)
     *     - Tag overlap with user's preferred tags
     */
    get: operations["get_recommended_content_content_recommended_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/content/{item_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Content Item
     * @description Get a specific content item.
     *
     *     - Only returns if item belongs to current user
     *     - Returns 404 if not found or deleted
     */
    get: operations["get_content_item_content__item_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Content Item
     * @description Soft delete a content item.
     *
     *     - Sets deleted_at timestamp
     *     - Item won't appear in lists anymore
     *     - Can be restored later (if we build that feature)
     */
    delete: operations["delete_content_item_content__item_id__delete"];
    options?: never;
    head?: never;
    /**
     * Update Content Item
     * @description Update a content item.
     *
     *     - Can mark as read/unread
     *     - Can archive/unarchive
     */
    patch: operations["update_content_item_content__item_id__patch"];
    trace?: never;
  };
  "/content/{item_id}/full": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Content Item Full
     * @description Get a content item with full text.
     *
     *     - Returns complete article content
     *     - Use this for reading view
     */
    get: operations["get_content_item_full_content__item_id__full_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/content/{item_id}/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate Content Summary
     * @description Trigger summary generation for a content item.
     */
    post: operations["generate_content_summary_content__item_id__summary_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/content/{item_id}/tags/accept": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Accept Auto Tags
     * @description Accept auto-generated tags for an item.
     *     Copies auto_tags → tags.
     */
    post: operations["accept_auto_tags_content__item_id__tags_accept_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/content/{item_id}/tags/dismiss": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Dismiss Auto Tags
     * @description Dismiss auto-generated tags for an item.
     *     Clears auto_tags, keeps user's tags unchanged.
     */
    post: operations["dismiss_auto_tags_content__item_id__tags_dismiss_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/content/{content_id}/highlights": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Highlights
     * @description Get all highlights for a content item
     */
    get: operations["get_highlights_content__content_id__highlights_get"];
    put?: never;
    /**
     * Create Highlight
     * @description Create a new highlight on a content item
     */
    post: operations["create_highlight_content__content_id__highlights_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/highlights/{highlight_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Highlight
     * @description Delete a highlight
     */
    delete: operations["delete_highlight_highlights__highlight_id__delete"];
    options?: never;
    head?: never;
    /**
     * Update Highlight
     * @description Update a highlight's note or color
     */
    patch: operations["update_highlight_highlights__highlight_id__patch"];
    trace?: never;
  };
  "/lists": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get User Lists
     * @description Get all lists for current user.
     *     Includes count of items in each list.
     */
    get: operations["get_user_lists_lists_get"];
    put?: never;
    /**
     * Create List
     * @description Create a new list.
     */
    post: operations["create_list_lists_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/lists/{list_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get List
     * @description Get a specific list.
     */
    get: operations["get_list_lists__list_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete List
     * @description Delete a list.
     *     Note: This doesn't delete the content items, just the list and memberships.
     */
    delete: operations["delete_list_lists__list_id__delete"];
    options?: never;
    head?: never;
    /**
     * Update List
     * @description Update a list's name, description, or sharing status.
     */
    patch: operations["update_list_lists__list_id__patch"];
    trace?: never;
  };
  "/lists/{list_id}/content": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get List Content
     * @description Get all content items in a list.
     */
    get: operations["get_list_content_lists__list_id__content_get"];
    put?: never;
    /**
     * Add Content To List
     * @description Add content items to a list.
     */
    post: operations["add_content_to_list_lists__list_id__content_post"];
    /**
     * Remove Content From List
     * @description Remove content items from a list.
     */
    delete: operations["remove_content_from_list_lists__list_id__content_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/lists/{list_id}/highlights": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get List Highlights
     * @description Get all highlights across all content items in a list.
     *     Used by the writing workspace source pane.
     */
    get: operations["get_list_highlights_lists__list_id__highlights_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/search/semantic": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Semantic Search
     * @description Search content using hybrid routing: keyword, filter, semantic, or RRF fusion.
     *
     *     The query is classified automatically:
     *     - Short keywords → full-text tsvector search (fast, no API call)
     *     - Known author/tag/domain → SQL filter (fast, no API call)
     *     - Natural language questions → semantic embedding search
     *     - Longer conceptual phrases → keyword + semantic fused with RRF
     */
    get: operations["semantic_search_search_semantic_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/search/connections/{highlight_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Find Highlight Connections
     * @description Find highlights similar to the given highlight across all user's articles.
     *
     *     - Searches based on highlight embeddings
     *     - Returns similar highlights from other articles
     *     - Excludes highlights from the same article
     */
    get: operations["find_highlight_connections_search_connections__highlight_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/search/connections/article/{content_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Find Article Connections
     * @description Find all cross-article connections for highlights in the given article.
     *
     *     - Groups connections by connected article
     *     - Shows which highlights connect to other articles
     *     - Returns sorted by total similarity score
     */
    get: operations["find_article_connections_search_connections_article__content_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/search/{item_id}/similar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Find Similar Content
     * @description Find content items similar to the given item.
     *
     *     - Uses cosine similarity on embeddings
     *     - Returns most similar items first
     *     - Only searches user's own content
     */
    get: operations["find_similar_content_search__item_id__similar_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/analytics/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get User Stats
     * @description Get basic statistics about user's content
     */
    get: operations["get_user_stats_analytics_stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/vinyl": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Vinyl Records
     * @description Get all vinyl records for the current user.
     */
    get: operations["get_vinyl_records_vinyl_get"];
    put?: never;
    /**
     * Create Vinyl Record
     * @description Create a new vinyl record from a Discogs URL.
     *     This session only creates the skeleton; the metadata is fetched in the background.
     */
    post: operations["create_vinyl_record_vinyl_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/vinyl/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Vinyl Record
     * @description Get a specific vinyl record by ID.
     */
    get: operations["get_vinyl_record_vinyl__id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Vinyl Record
     * @description Soft delete a vinyl record.
     */
    delete: operations["delete_vinyl_record_vinyl__id__delete"];
    options?: never;
    head?: never;
    /**
     * Update Vinyl Record
     * @description Update a vinyl record's user-provided fields.
     */
    patch: operations["update_vinyl_record_vinyl__id__patch"];
    trace?: never;
  };
  "/lists/{list_id}/draft": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Draft
     * @description Get the draft for a list. Returns 404 if no draft exists yet.
     */
    get: operations["get_draft_lists__list_id__draft_get"];
    put?: never;
    /**
     * Create Draft
     * @description Create a new draft for a list. Only one draft per list per user.
     */
    post: operations["create_draft_lists__list_id__draft_post"];
    /**
     * Delete Draft
     * @description Delete the draft for a list.
     */
    delete: operations["delete_draft_lists__list_id__draft_delete"];
    options?: never;
    head?: never;
    /**
     * Update Draft
     * @description Update the draft content (autosave target). Creates draft if it doesn't exist.
     */
    patch: operations["update_draft_lists__list_id__draft_patch"];
    trace?: never;
  };
  "/public/u/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Public Profile
     * @description Fetch user profile details. Only succeeds if user.is_public == True.
     */
    get: operations["get_public_profile_public_u__username__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/public/u/{username}/content": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Public Content
     * @description Fetch the user's public queue items.
     */
    get: operations["get_public_content_public_u__username__content_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/public/u/{username}/content/{item_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Public Content Item
     * @description Fetch a single public content item by ID.
     */
    get: operations["get_public_content_item_public_u__username__content__item_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/public/u/{username}/vinyl": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Public Vinyl
     * @description Fetch the user's public vinyl records.
     */
    get: operations["get_public_vinyl_public_u__username__vinyl_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/.well-known/oauth-protected-resource": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Oauth Protected Resource
     * @description RFC 9728 OAuth 2.0 Protected Resource Metadata.
     *     Required by MCP 2025-11-25 spec — clients fetch this first to discover
     *     the authorization server URL before starting the OAuth flow.
     */
    get: operations["oauth_protected_resource__well_known_oauth_protected_resource_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/.well-known/oauth-authorization-server": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Oauth Discovery
     * @description RFC 8414 OAuth 2.0 Authorization Server Metadata.
     *     MCP clients fetch this to discover authorize/token endpoints.
     *     Advertises dynamic client registration so mcp-remote can self-register.
     */
    get: operations["oauth_discovery__well_known_oauth_authorization_server_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/mcp-transport/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Dynamic Client Registration
     * @description RFC 7591 Dynamic Client Registration.
     *     mcp-remote requires this endpoint to exist — it self-registers before
     *     starting the OAuth flow. We accept any client and echo back a client_id
     *     derived from the request (no client secret needed, PKCE-only flow).
     */
    post: operations["dynamic_client_registration_mcp_transport_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/mcp-transport/authorize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Authorize Get
     * @description Show the login form.
     */
    get: operations["authorize_get_mcp_transport_authorize_get"];
    put?: never;
    /**
     * Authorize Post
     * @description Validate credentials, store auth code in Redis, redirect to client.
     */
    post: operations["authorize_post_mcp_transport_authorize_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/mcp-transport/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Token
     * @description Exchange an auth code + PKCE verifier, or refresh token, for a sed.i JWT.
     */
    post: operations["token_mcp_transport_token_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/test/pdf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Serve Test Pdf
     * @description Serve the sample PDF for testing PDF ingestion.
     *
     *     Usage: Paste http://localhost:8000/api/test/pdf into the app URL input.
     */
    get: operations["serve_test_pdf_api_test_pdf_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/test/pdf_chem": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Serve Test Pdf Chem
     * @description Serve the sample PDF for testing PDF ingestion.
     *
     *     Usage: Paste http://localhost:8000/api/test/pdf into the app URL input.
     */
    get: operations["serve_test_pdf_chem_api_test_pdf_chem_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Root */
    get: operations["root__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations["health_check_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AddContentToList
     * @description Add content items to a list
     */
    AddContentToList: {
      /** Content Item Ids */
      content_item_ids: string[];
    };
    /**
     * ArticleConnection
     * @description A connection between articles
     */
    ArticleConnection: {
      /** Article Id */
      article_id: string;
      /** Article Title */
      article_title: string;
      /** Highlight Pairs */
      highlight_pairs: {
        [key: string]: unknown;
      }[];
      /** Total Similarity */
      total_similarity: number;
    };
    /** Body_authorize_post_mcp_transport_authorize_post */
    Body_authorize_post_mcp_transport_authorize_post: {
      /** Client Id */
      client_id: string;
      /** Redirect Uri */
      redirect_uri: string;
      /** Code Challenge */
      code_challenge: string;
      /** Email */
      email: string;
      /** Password */
      password: string;
      /**
       * State
       * @default
       */
      state: string;
      /**
       * Code Challenge Method
       * @default S256
       */
      code_challenge_method: string;
    };
    /** Body_login_auth_login_post */
    Body_login_auth_login_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /**
       * Password
       * Format: password
       */
      password: string;
      /**
       * Scope
       * @default
       */
      scope: string;
      /** Client Id */
      client_id?: string | null;
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null;
    };
    /** Body_token_mcp_transport_token_post */
    Body_token_mcp_transport_token_post: {
      /** Grant Type */
      grant_type: string;
      /** Client Id */
      client_id: string;
      /** Code */
      code?: string | null;
      /** Redirect Uri */
      redirect_uri?: string | null;
      /** Code Verifier */
      code_verifier?: string | null;
      /** Refresh Token */
      refresh_token?: string | null;
    };
    /**
     * ContentItemCreate
     * @description Data needed to save a new link
     */
    ContentItemCreate: {
      /** Url */
      url: string;
      /** List Ids */
      list_ids?: string[] | null;
      /** Pre Extracted Html */
      pre_extracted_html?: string | null;
      /** Pre Extracted Title */
      pre_extracted_title?: string | null;
      /** Pre Extracted Author */
      pre_extracted_author?: string | null;
      /** Pre Extracted Description */
      pre_extracted_description?: string | null;
      /** Pre Extracted Thumbnail */
      pre_extracted_thumbnail?: string | null;
      /** Pre Extracted Published Date */
      pre_extracted_published_date?: string | null;
      /**
       * Pre Extracted Access Restricted
       * @default false
       */
      pre_extracted_access_restricted: boolean;
    };
    /**
     * ContentItemDetail
     * @description Extended response with full text for single item view
     */
    ContentItemDetail: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Original Url */
      original_url: string;
      /** Title */
      title: string | null;
      /** Description */
      description: string | null;
      /** Thumbnail Url */
      thumbnail_url: string | null;
      /** Content Type */
      content_type: string | null;
      /** Summary */
      summary: string | null;
      /**
       * Tags
       * @default []
       */
      tags: string[] | null;
      /**
       * Auto Tags
       * @default []
       */
      auto_tags: string[] | null;
      /** Status */
      status?: string | null;
      /** Full Text */
      full_text: string | null;
      /** Word Count */
      word_count: number | null;
      /** Reading Time Minutes */
      reading_time_minutes: number | null;
      /**
       * Read Position
       * @default 0
       */
      read_position: number | null;
      /** Author */
      author?: string | null;
      /** Published Date */
      published_date?: string | null;
      /**
       * Content Vertical
       * @default general
       */
      content_vertical: string | null;
      /** Vertical Metadata */
      vertical_metadata?: {
        [key: string]: unknown;
      } | null;
      /** Is Read */
      is_read: boolean;
      /** Is Archived */
      is_archived: boolean;
      /** Is Public */
      is_public: boolean;
      /** Processing Status */
      processing_status: string;
      /** Processing Error */
      processing_error?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /**
       * Reading Status
       * @description Compute reading status from is_read, read_position, and is_archived.
       *
       *     Priority:
       *     1. Archived items are always "archived"
       *     2. Items explicitly marked as read stay "read" (don't change based on position)
       *     3. Items with position >= 0.9 are "read" (auto-mark as complete)
       *     4. Items with position > 0 are "in_progress"
       *     5. Otherwise "unread"
       */
      readonly reading_status: string;
    };
    /**
     * ContentItemList
     * @description Paginated list response
     */
    ContentItemList: {
      /** Items */
      items: components["schemas"]["ContentItemResponse"][];
      /** Total */
      total: number;
      /** Skip */
      skip: number;
      /** Limit */
      limit: number;
    };
    /**
     * ContentItemResponse
     * @description What we return to the client
     */
    ContentItemResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Original Url */
      original_url: string;
      /** Title */
      title: string | null;
      /** Description */
      description: string | null;
      /** Thumbnail Url */
      thumbnail_url: string | null;
      /** Content Type */
      content_type: string | null;
      /** Summary */
      summary: string | null;
      /**
       * Tags
       * @default []
       */
      tags: string[] | null;
      /**
       * Auto Tags
       * @default []
       */
      auto_tags: string[] | null;
      /** Status */
      status?: string | null;
      /** Full Text */
      full_text: string | null;
      /** Word Count */
      word_count: number | null;
      /** Reading Time Minutes */
      reading_time_minutes: number | null;
      /**
       * Read Position
       * @default 0
       */
      read_position: number | null;
      /** Author */
      author?: string | null;
      /** Published Date */
      published_date?: string | null;
      /**
       * Content Vertical
       * @default general
       */
      content_vertical: string | null;
      /** Vertical Metadata */
      vertical_metadata?: {
        [key: string]: unknown;
      } | null;
      /** Is Read */
      is_read: boolean;
      /** Is Archived */
      is_archived: boolean;
      /** Is Public */
      is_public: boolean;
      /** Processing Status */
      processing_status: string;
      /** Processing Error */
      processing_error?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /**
       * Reading Status
       * @description Compute reading status from is_read, read_position, and is_archived.
       *
       *     Priority:
       *     1. Archived items are always "archived"
       *     2. Items explicitly marked as read stay "read" (don't change based on position)
       *     3. Items with position >= 0.9 are "read" (auto-mark as complete)
       *     4. Items with position > 0 are "in_progress"
       *     5. Otherwise "unread"
       */
      readonly reading_status: string;
    };
    /**
     * ContentItemUpdate
     * @description Fields that can be updated
     */
    ContentItemUpdate: {
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
      /** Thumbnail Url */
      thumbnail_url?: string | null;
      /**
       * Content Type
       * @default unknown
       */
      content_type: string | null;
      /** Author */
      author?: string | null;
      /** Published Date */
      published_date?: string | null;
      /**
       * Content Vertical
       * @default general
       */
      content_vertical: string | null;
      /** Vertical Metadata */
      vertical_metadata?: {
        [key: string]: unknown;
      } | null;
      /** Is Read */
      is_read?: boolean | null;
      /** Is Archived */
      is_archived?: boolean | null;
      /** Is Public */
      is_public?: boolean | null;
      /** Read Position */
      read_position?: number | null;
      /** Tags */
      tags?: string[] | null;
      /** Auto Tags */
      auto_tags?: string[] | null;
      /** Full Text */
      full_text?: string | null;
    };
    /** DeleteAccountRequest */
    DeleteAccountRequest: {
      /** Password */
      password: string;
    };
    /** DraftCreate */
    DraftCreate: {
      /**
       * Content
       * @description Raw markdown content
       * @default
       */
      content: string;
      /**
       * Title
       * @description Optional title (derived from first heading if absent)
       */
      title?: string | null;
      /**
       * Word Count
       * @default 0
       */
      word_count: number;
    };
    /** DraftResponse */
    DraftResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * List Id
       * Format: uuid
       */
      list_id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Title */
      title: string | null;
      /** Content */
      content: string;
      /** Word Count */
      word_count: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** DraftUpdate */
    DraftUpdate: {
      /** Content */
      content?: string | null;
      /** Title */
      title?: string | null;
      /** Word Count */
      word_count?: number | null;
    };
    /** ForgotPasswordRequest */
    ForgotPasswordRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** GenericMessage */
    GenericMessage: {
      /** Message */
      message: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HighlightConnection
     * @description A highlight that connects to another highlight
     */
    HighlightConnection: {
      /** Id */
      id: string;
      /** Text */
      text: string;
      /** Color */
      color: string;
      /** Similarity Score */
      similarity_score: number;
    };
    /**
     * HighlightConnectionResponse
     * @description Response with highlight and its connections
     */
    HighlightConnectionResponse: {
      item: components["schemas"]["HighlightConnection"];
      /** From Article Id */
      from_article_id: string;
      /** From Article Title */
      from_article_title: string;
    };
    /** HighlightCreate */
    HighlightCreate: {
      /**
       * Text
       * @description The highlighted text
       */
      text: string;
      /**
       * Note
       * @description Optional annotation
       */
      note?: string | null;
      /**
       * Start Offset
       * @description Character position where highlight starts
       */
      start_offset: number;
      /**
       * End Offset
       * @description Character position where highlight ends
       */
      end_offset: number;
      /**
       * Color
       * @description Highlight color
       * @default yellow
       */
      color: string;
    };
    /** HighlightResponse */
    HighlightResponse: {
      /**
       * Text
       * @description The highlighted text
       */
      text: string;
      /**
       * Note
       * @description Optional annotation
       */
      note?: string | null;
      /**
       * Start Offset
       * @description Character position where highlight starts
       */
      start_offset: number;
      /**
       * End Offset
       * @description Character position where highlight ends
       */
      end_offset: number;
      /**
       * Color
       * @description Highlight color
       * @default yellow
       */
      color: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Content Item Id
       * Format: uuid
       */
      content_item_id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** HighlightUpdate */
    HighlightUpdate: {
      /** Note */
      note?: string | null;
      /** Color */
      color?: string | null;
    };
    /**
     * ListCreate
     * @description Data needed to create a list
     */
    ListCreate: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /**
       * Is Shared
       * @default false
       */
      is_shared: boolean;
    };
    /**
     * ListResponse
     * @description What we return for a list
     */
    ListResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /**
       * Owner Id
       * Format: uuid
       */
      owner_id: string;
      /** Is Shared */
      is_shared: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ListUpdate
     * @description Fields that can be updated
     */
    ListUpdate: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Is Shared */
      is_shared?: boolean | null;
    };
    /**
     * ListWithContentCount
     * @description List with count of items
     */
    ListWithContentCount: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /**
       * Owner Id
       * Format: uuid
       */
      owner_id: string;
      /** Is Shared */
      is_shared: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Content Count */
      content_count: number;
    };
    /**
     * RemoveContentFromList
     * @description Remove content items from a list
     */
    RemoveContentFromList: {
      /** Content Item Ids */
      content_item_ids: string[];
    };
    /** ResetPasswordRequest */
    ResetPasswordRequest: {
      /** Token */
      token: string;
      /** New Password */
      new_password: string;
    };
    /**
     * SimilarContentResponse
     * @description Response for similar content
     */
    SimilarContentResponse: {
      item: components["schemas"]["ContentItemResponse"];
      /** Similarity Score */
      similarity_score: number;
      /**
       * Match Type
       * @default semantic
       */
      match_type: string;
      /** Semantic Score */
      semantic_score?: number | null;
    };
    /**
     * Token
     * @description JWT token response
     */
    Token: {
      /** Access Token */
      access_token: string;
      /** Token Type */
      token_type: string;
    };
    /**
     * UserCreate
     * @description Data needed to register a new user
     */
    UserCreate: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /** Username */
      username: string;
      /** Full Name */
      full_name?: string | null;
    };
    /**
     * UserResponse
     * @description What we return to the client (no password!)
     */
    UserResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Username */
      username: string | null;
      /** Full Name */
      full_name: string | null;
      /** Is Active */
      is_active: boolean;
      /** Is Public */
      is_public: boolean;
      /** Is Queue Public */
      is_queue_public: boolean;
      /** Is Crates Public */
      is_crates_public: boolean;
      /** Is Verified */
      is_verified: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * UserUpdate
     * @description Fields that can be updated on a user profile
     */
    UserUpdate: {
      /** Full Name */
      full_name?: string | null;
      /** Username */
      username?: string | null;
      /** Is Public */
      is_public?: boolean | null;
      /** Is Queue Public */
      is_queue_public?: boolean | null;
      /** Is Crates Public */
      is_crates_public?: boolean | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VinylRecordCreate */
    VinylRecordCreate: {
      /** Discogs Url */
      discogs_url: string;
    };
    /** VinylRecordResponse */
    VinylRecordResponse: {
      /** Title */
      title?: string | null;
      /** Artist */
      artist?: string | null;
      /** Label */
      label?: string | null;
      /** Catalog Number */
      catalog_number?: string | null;
      /** Year */
      year?: number | null;
      /** Cover Url */
      cover_url?: string | null;
      /**
       * Genres
       * @default []
       */
      genres: string[];
      /**
       * Styles
       * @default []
       */
      styles: string[];
      /** Notes */
      notes?: string | null;
      /** Rating */
      rating?: number | null;
      /**
       * Tags
       * @default []
       */
      tags: string[];
      /**
       * Status
       * @default collection
       */
      status: string;
      /**
       * Is Public
       * @default false
       */
      is_public: boolean;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Discogs Url */
      discogs_url: string;
      /** Discogs Release Id */
      discogs_release_id?: number | null;
      /**
       * Tracklist
       * @default []
       */
      tracklist: components["schemas"]["VinylTrack"][];
      /**
       * Videos
       * @default []
       */
      videos: components["schemas"]["VinylVideo"][];
      /** Processing Status */
      processing_status: string;
      /** Processing Error */
      processing_error?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** VinylRecordUpdate */
    VinylRecordUpdate: {
      /** Title */
      title?: string | null;
      /** Artist */
      artist?: string | null;
      /** Label */
      label?: string | null;
      /** Year */
      year?: number | null;
      /** Cover Url */
      cover_url?: string | null;
      /** Genres */
      genres?: string[] | null;
      /** Styles */
      styles?: string[] | null;
      /** Notes */
      notes?: string | null;
      /** Rating */
      rating?: number | null;
      /** Tags */
      tags?: string[] | null;
      /** Status */
      status?: string | null;
      /** Is Public */
      is_public?: boolean | null;
      /** Videos */
      videos?: components["schemas"]["VinylVideo"][] | null;
    };
    /** VinylTrack */
    VinylTrack: {
      /** Position */
      position: string;
      /** Title */
      title: string;
      /** Duration */
      duration?: string | null;
    };
    /** VinylVideo */
    VinylVideo: {
      /** Title */
      title?: string | null;
      /** Uri */
      uri: string;
      /** Duration */
      duration?: number | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  register_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  verify_email_auth_verify_email_get: {
    parameters: {
      query: {
        token: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericMessage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  forgot_password_auth_forgot_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericMessage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reset_password_auth_reset_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericMessage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_current_user_info_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  update_current_user_info_auth_me_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_current_user_auth_me_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteAccountRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_content_items_content_get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
        is_read?: boolean | null;
        is_archived?: boolean | null;
        tag?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContentItemList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_content_item_content_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContentItemCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContentItemResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_tags_content_tags_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown[];
        };
      };
    };
  };
  get_recommended_content_content_recommended_get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
        mood?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContentItemList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_content_item_content__item_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContentItemResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_content_item_content__item_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_content_item_content__item_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContentItemUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContentItemResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_content_item_full_content__item_id__full_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContentItemDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  generate_content_summary_content__item_id__summary_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  accept_auto_tags_content__item_id__tags_accept_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  dismiss_auto_tags_content__item_id__tags_dismiss_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_highlights_content__content_id__highlights_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        content_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HighlightResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_highlight_content__content_id__highlights_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        content_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["HighlightCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HighlightResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_highlight_highlights__highlight_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        highlight_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_highlight_highlights__highlight_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        highlight_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["HighlightUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HighlightResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_lists_lists_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListWithContentCount"][];
        };
      };
    };
  };
  create_list_lists_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ListCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_list_lists__list_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_list_lists__list_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_list_lists__list_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ListUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_list_content_lists__list_id__content_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContentItemResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_content_to_list_lists__list_id__content_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddContentToList"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_content_from_list_lists__list_id__content_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RemoveContentFromList"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_list_highlights_lists__list_id__highlights_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HighlightResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  semantic_search_search_semantic_get: {
    parameters: {
      query: {
        query: string;
        limit?: number;
        offset?: number;
        mode?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SimilarContentResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  find_highlight_connections_search_connections__highlight_id__get: {
    parameters: {
      query?: {
        threshold?: number;
        limit?: number;
      };
      header?: never;
      path: {
        highlight_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HighlightConnectionResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  find_article_connections_search_connections_article__content_id__get: {
    parameters: {
      query?: {
        threshold?: number;
      };
      header?: never;
      path: {
        content_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArticleConnection"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  find_similar_content_search__item_id__similar_get: {
    parameters: {
      query?: {
        threshold?: number;
        limit?: number;
      };
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SimilarContentResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_stats_analytics_stats_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  get_vinyl_records_vinyl_get: {
    parameters: {
      query?: {
        /** @description Filter by status (collection, wantlist, library) */
        status?: string | null;
        /** @description Sort field (created_at, year, artist) */
        sort_by?: string;
        /** @description Sort order (asc, desc) */
        sort_order?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VinylRecordResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_vinyl_record_vinyl_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VinylRecordCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VinylRecordResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_vinyl_record_vinyl__id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VinylRecordResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_vinyl_record_vinyl__id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_vinyl_record_vinyl__id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VinylRecordUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VinylRecordResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_draft_lists__list_id__draft_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_draft_lists__list_id__draft_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DraftCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_draft_lists__list_id__draft_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_draft_lists__list_id__draft_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DraftUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_public_profile_public_u__username__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_public_content_public_u__username__content_get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
      };
      header?: never;
      path: {
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContentItemList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_public_content_item_public_u__username__content__item_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContentItemResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_public_vinyl_public_u__username__vinyl_get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
      };
      header?: never;
      path: {
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VinylRecordResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  oauth_protected_resource__well_known_oauth_protected_resource_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  oauth_discovery__well_known_oauth_authorization_server_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  dynamic_client_registration_mcp_transport_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  authorize_get_mcp_transport_authorize_get: {
    parameters: {
      query: {
        client_id: string;
        redirect_uri: string;
        response_type: string;
        code_challenge: string;
        code_challenge_method?: string;
        state?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": string;
        };
      };
      /** @description Invalid OAuth authorization request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  authorize_post_mcp_transport_authorize_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_authorize_post_mcp_transport_authorize_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": string;
        };
      };
      /** @description Invalid OAuth authorization request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  token_mcp_transport_token_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_token_mcp_transport_token_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Invalid OAuth token exchange request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  serve_test_pdf_api_test_pdf_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  serve_test_pdf_chem_api_test_pdf_chem_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  root__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
