[phases.setup]
nixPkgs = ["python311", "poetry"]

[phases.install]
cmds = [
  "rm -rf .venv",
  "poetry install --no-root --only main"
]

[start]
cmd = "poetry run celery -A app.core.celery_app worker --loglevel=info --concurrency=2 --pool=solo --beat"
